### ISSUE TITLE
MH-ET LIVE ESP32 DEVKIT 5v PIN

### ISSUE THREAD

**Issue by prashantkumar99** [MHEtLive/ESP32-DEVKIT#1]
What is the use of 5v pin present on board MH-ET LIVE ESP32 DEVKIT as shown in the picure below.
@MHEtLive 
![mh-et-live_esp32-devkit_photobottom](https://user-images.githubusercontent.com/40118611/41191926-33b92c72-6c14-11e8-91db-c2463ef8f5dc.jpg)

**Comment by MHEtLive** [comment]
It is connected to the USB-POWER, you can consider it as VUSB. Can be use to Provide power for external devices.

**Comment by prashantkumar99** [comment]
Thanks for reply @MHEtLive 
It was to the point.
Also since it is connected to USB and can provide power. Can it be used as power input for MH-ET ESP32 DEVKIT board with 5V power supply just like 3V3 pin which uses 3.3V power supply.

**Comment by MHEtLive** [comment]
@pksgithubid YES. It can be used as input. Remember just 5v.

**Comment by prashantkumar99** [comment]
@MHEtLive  Thanks for reply.
